[tool.mypy]
python_version = "3.13"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
check_untyped_defs = true

[tool.ruff.lint]
extend-ignore = ["E501","PLR0913", "PLR2004", "PLR2004", "PLR0912", "PLW2901"]
extend-select = [
  "UP",  # pyupgrade
  "D",   # pydocstyle
  "I",   # isort
  "E",   # flake8-errors
  "W",   # flake8-warnings
  "Q",   # flake8-quotes
  "F",   # flake8-pyflakes
  "B",   # flake8-bugbear
  "C4",  # flake8-comprehensions
  "S",   # flake8-bandit
  "RSE", # flake8-raise
  "BLE", # flake8-blind-except
  #"T20", # flake8-print
  "T10", # flake8-debugger
  "SIM", # flake8-simplify
  "PL",  # Pylint
  "RUF",  # Ruff
  "DTZ",  # flake8-datetimez
  "ERA",  # eradicate
  "PERF",# Perflint
  
  #"PD",   # pandas-vet
  "FIX",
  "RUF",  # Ruff
  #"T20",  # flake8-print # only in prod
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"common_alg/technique/two_pointers.py" = ["ERA001"]
"common_alg/technique/sliding_window.py" = ["ERA001"]
"common_alg/technique/linked_list.py" = ["ERA001"]
"common_alg/statistic/statistic.ipynb" = ["ERA001"]